apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo
  namespace: argocd
  labels:
    app: bookinfo
    environment: prod
spec:
  destination:
    namespace: bookinfo
    server: https://kubernetes.default.svc
  project: bookinfo
  source:
    kustomize:
    path: deploy/overlays/prod
    repoURL: https://github.com/flaviolnx/bookinfo-argo
    targetRevision: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true 
      - CreateNamespace=true
