apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: install-kiali-ossm-operator
  namespace: ossm-polices
  annotations:
    policy.open-cluster-management.io/description: Install Kiali Operator
    policy.open-cluster-management.io/categories: ""
    policy.open-cluster-management.io/standards: ""
    policy.open-cluster-management.io/controls: ""
spec:
  disabled: false
  remediationAction: enforce
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1beta1
        kind: OperatorPolicy
        metadata:
          name: install-ossm-kiali
        spec:
          remediationAction: enforce
          severity: critical
          complianceType: musthave
          subscription:
            name: kiali-ossm
            namespace: openshift-operators
            channel: stable
            source: redhat-operators
            sourceNamespace: openshift-marketplace
            startingCSV: kiali-operator.v2.17.1
          upgradeApproval: Automatic
          versions:
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: install-kiali-ossm-operator-placement
  namespace: ossm-polices
spec:
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
  clusterSets:
    - prod-cluster
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: environment
              operator: In
              values:
                - prod
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: install-kiali-ossm-operator-placement
  namespace: ossm-polices
placementRef:
  name: install-kiali-ossm-operator-placement
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: install-kiali-ossm-operator
    apiGroup: policy.open-cluster-management.io
    kind: Policy