apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: install-service-mesh-3-operator
  namespace: ossm-polices
  annotations:
    policy.open-cluster-management.io/categories: ""
    policy.open-cluster-management.io/controls: ""
    policy.open-cluster-management.io/standards: ""
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1beta1
        kind: OperatorPolicy
        metadata:
          name: install-operator
        spec:
          complianceType: musthave
          remediationAction: enforce
          severity: critical
          subscription:
            name: servicemeshoperator3
            namespace: istio-system
            channel: stable
            source: redhat-operators
            sourceNamespace: openshift-marketplace
            startingCSV: servicemeshoperator3.v3.2.0
          upgradeApproval: Automatic
          versions:
  remediationAction: enforce
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: install-service-mesh-3-operator-placement
  namespace: default
spec:
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
  clusterSets:
    - prod-cluster
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: environment
              operator: In
              values:
                - prod
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: install-service-mesh-3-operator-placement
  namespace: default
placementRef:
  name: install-service-mesh-3-operator-placement
  kind: Placement
  apiGroup: cluster.open-cluster-management.io
subjects:
  - name: install-service-mesh-3-operator
    kind: Policy
    apiGroup: policy.open-cluster-management.io
