apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: install-tempo-operator
  namespace: ossm-polices
  annotations:
    policy.open-cluster-management.io/description: Install Tempo Operator
    policy.open-cluster-management.io/categories: ""
    policy.open-cluster-management.io/standards: ""
    policy.open-cluster-management.io/controls: ""
spec:
  disabled: false
  remediationAction: enforce
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1beta1
        kind: OperatorPolicy
        metadata:
          name: install-tempo-operator
        spec:
          remediationAction: enforce
          severity: critical
          complianceType: musthave
          subscription:
            name: tempo-product
            namespace: openshift-tempo-operator
            channel: stable
            source: redhat-operators
            sourceNamespace: openshift-marketplace
            startingCSV: tempo-operator.v0.19.0-1
          upgradeApproval: Automatic
          versions:
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: install-tempo-operator-placement
  namespace: ossm-polices
spec:
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
  clusterSets:
    - prod-cluster
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: environment
              operator: In
              values:
                - prod
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: install-tempo-operator-placement
  namespace: ossm-polices
placementRef:
  name: install-tempo-operator-placement
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: install-tempo-operator
    apiGroup: policy.open-cluster-management.io
    kind: Policy
