apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo-application
  namespace: openshift-gitops # Replace with your ArgoCD installation namespace
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: bookinfo # Target namespace for the application
  project: default
  source:
    # Official Istio repository for application manifests
    repoURL: https://github.com/istio/istio.git 
    path: samples/bookinfo/platform/kube # Path containing standard Bookinfo Deployments/Services
    targetRevision: master 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true