apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-mesh-control-plane
  namespace: openshift-gitops # Replace with your ArgoCD installation namespace
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system # Target namespace for the control plane components
  project: default
  source:
    # ⚠️ Replace with the URL of your actual Git repository containing k8s-manifests/
    repoURL: https://github.com/flaviolnx/rhone-sm3.git 
    path: k8s-manifests/control-plane
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 
      - ServerSideApply=true 
      # Allows synchronization of resources targeting namespaces outside 'istio-system' (e.g., SMMR targeting 'bookinfo')
      - ApplyOutOfSyncOnly=true 

---