---
# OpenTelemetry Collector (receives traces from Istio and forwards to Tempo)
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: opentelemetry-collector
  namespace: istio-system
spec:
  mode: deployment
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
    exporters:
      # Tempo Exporter (endpoint depends on your TempoStack service)
      otlp:
        endpoint: tempo-server.monitoring.svc.cluster.local:4317 
    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [otlp]

---
# Kiali Configuration (minimal)
apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali-cr
  namespace: istio-system
spec:
  deployment:
    ingress:
      enabled: true

---
# Grafana Tempo Stack (assuming 'tempo-operator' is installed)
apiVersion: tempo.grafana.com/v1alpha1
kind: TempoStack
metadata:
  name: basic-tempo
  namespace: istio-system
spec:
  # Minimal configuration for testing/quick deployment
  storage:
    secret:
      name: tempo-secret # Requires a pre-created secret for S3/storage config
    backend: filesystem
  # ... Add more specific Tempo configuration as needed